"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = []
OPTIONS = {
 'iconfile': 'app_icon.icns',
 'resources': 'vpn_off.png,vpn_on.png'}

setup(
    app=APP,
    name="AutoVPN",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
